version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - gradle-cache:/home/gradle/.gradle
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/boatdb
      SPRING_DATASOURCE_USERNAME: boatuser
      SPRING_DATASOURCE_PASSWORD: boatpass
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: boatdb
      MYSQL_USER: boatuser
      MYSQL_PASSWORD: boatpass
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  gradle-cache:
  db-data:
